/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conjuntos;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author win7
 */
public class GUI extends javax.swing.JFrame {
    DefaultListModel<String> model_conjunto_a;
    DefaultListModel<String> model_conjunto_b;
    DefaultListModel<Integer> model_conjunto_c;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        this.setTitle("Conjuntos");
        this.setResizable(false);
        
        model_conjunto_a = new DefaultListModel<>();
        this.jList_conjunto_a.setModel(model_conjunto_a);
        
        model_conjunto_b = new DefaultListModel<>();
        this.jList_conjunto_b.setModel(model_conjunto_b);
        
        model_conjunto_c = new DefaultListModel<>();
        this.jList_conjunto_c.setModel(model_conjunto_c);
        
        // Agregar items al combo box
        String operaciones [] = {"--Selecionar--", "Unión", "Intersección", "A-B", "B-A", "Diferencia Sim."};
        for (int k = 0; k < operaciones.length; k++) {
            this.jComboBox_operaciones.addItem(operaciones[k]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_elemento_a = new javax.swing.JTextField();
        jButton_agregar_a = new javax.swing.JButton();
        jButton_eliminar_a = new javax.swing.JButton();
        jButton_limpiar_a = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_conjunto_a = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_conjunto_b = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_elemento_b = new javax.swing.JTextField();
        jButton_agregar_b = new javax.swing.JButton();
        jButton_eliminar_b = new javax.swing.JButton();
        jButton_limpiar_b = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_conjunto_c = new javax.swing.JList<>();
        jComboBox_operaciones = new javax.swing.JComboBox<>();
        jButton_limpiar_todo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel1.setText("OPERACIONES CON CONJUNTOS");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel2.setText("Conjunto A");

        jLabel4.setText("Elemento: ");

        jButton_agregar_a.setText("Agregar");
        jButton_agregar_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_agregar_aMouseClicked(evt);
            }
        });

        jButton_eliminar_a.setText("Eliminar");
        jButton_eliminar_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_eliminar_aMouseClicked(evt);
            }
        });

        jButton_limpiar_a.setText("Limpiar");
        jButton_limpiar_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_limpiar_aMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jList_conjunto_a);

        jScrollPane2.setViewportView(jList_conjunto_b);

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel5.setText("Conjunto B");

        jLabel6.setText("Elemento: ");

        jButton_agregar_b.setText("Agregar");
        jButton_agregar_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_agregar_bMouseClicked(evt);
            }
        });

        jButton_eliminar_b.setText("Eliminar");
        jButton_eliminar_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_eliminar_bMouseClicked(evt);
            }
        });

        jButton_limpiar_b.setText("Limpiar");
        jButton_limpiar_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_limpiar_bMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel7.setText("Operaciones");

        jScrollPane3.setViewportView(jList_conjunto_c);

        jComboBox_operaciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_operacionesItemStateChanged(evt);
            }
        });

        jButton_limpiar_todo.setText("Limpiar Todo");
        jButton_limpiar_todo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_limpiar_todoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField_elemento_a)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton_agregar_a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_eliminar_a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_limpiar_a)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton_agregar_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_eliminar_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_limpiar_b))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField_elemento_b, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox_operaciones, 0, 186, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_limpiar_todo)
                                .addGap(44, 44, 44))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_elemento_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_agregar_a)
                            .addComponent(jButton_eliminar_a)
                            .addComponent(jButton_limpiar_a))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_elemento_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_agregar_b)
                            .addComponent(jButton_eliminar_b)
                            .addComponent(jButton_limpiar_b)
                            .addComponent(jButton_limpiar_todo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_agregar_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_agregar_aMouseClicked
        // TODO add your handling code here:
        String elemento = this.jTextField_elemento_a.getText();
        model_conjunto_a.addElement(elemento);
        this.jTextField_elemento_a.setText("");
    }//GEN-LAST:event_jButton_agregar_aMouseClicked

    private void jButton_eliminar_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_eliminar_aMouseClicked
        // TODO add your handling code here:
        String valor = this.jList_conjunto_a.getSelectedValue();
        int indice = this.jList_conjunto_a.getSelectedIndex();
        
        if (indice == -1) {
            JOptionPane.showMessageDialog(this, "Tienes que selecionar un elemento del conjunto A");
        } else {
            model_conjunto_a.remove(indice);
        }
    }//GEN-LAST:event_jButton_eliminar_aMouseClicked

    private void jButton_limpiar_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_limpiar_aMouseClicked
        // TODO add your handling code here:
        model_conjunto_a.clear();
    }//GEN-LAST:event_jButton_limpiar_aMouseClicked

    private void jButton_agregar_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_agregar_bMouseClicked
        // TODO add your handling code here:
        String elemento = this.jTextField_elemento_b.getText();
        model_conjunto_b.addElement(elemento);
        this.jTextField_elemento_b.setText("");
    }//GEN-LAST:event_jButton_agregar_bMouseClicked

    private void jButton_eliminar_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_eliminar_bMouseClicked
        // TODO add your handling code here:
        String valor = this.jList_conjunto_b.getSelectedValue();
        int indice = this.jList_conjunto_b.getSelectedIndex();
        
        if (indice == -1) {
            JOptionPane.showMessageDialog(this, "Tienes que selecionar un elemento del conjunto B");
        } else {
            model_conjunto_b.remove(indice);
        }
    }//GEN-LAST:event_jButton_eliminar_bMouseClicked

    private void jButton_limpiar_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_limpiar_bMouseClicked
        // TODO add your handling code here:
        model_conjunto_b.clear();
    }//GEN-LAST:event_jButton_limpiar_bMouseClicked

    private void jComboBox_operacionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_operacionesItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED) {
            // Item was just selected
            
            // Índice del item selecionado en el JComboBox de las operaciones
            int indice = this.jComboBox_operaciones.getSelectedIndex();
            System.out.println(indice);
            
            // Verificando que el usuario seleccione alguna operación
            if (indice > 0) {
                // Limpiando la lista para el conjunto C
                model_conjunto_c.clear();
                
                // Verificando que los conjuntos A y B tengan al menos un elemento
                int tamanio_a = model_conjunto_a.getSize();
                if (tamanio_a == 0) {
                    JOptionPane.showMessageDialog(this, "El conjunto A debe tener al menos un elemento");
                    return;
                }
                // Copiando los elementos del JList al conjunto A
                CConjunto conjunto_a = new CConjunto(tamanio_a);
                for (int k = 0; k < this.jList_conjunto_a.getModel().getSize();k++) {
                    conjunto_a.conjunto[k] = Integer.parseInt(this.jList_conjunto_a.getModel().getElementAt(k));
                }
                
                // Verificando que los conjuntos A y B tengan al menos un elemento
                int tamanio_b = model_conjunto_b.getSize();
                if (tamanio_a == 0) {
                    JOptionPane.showMessageDialog(this, "El conjunto B debe tener al menos un elemento");
                    return;
                }
                // Copiando los elementos del JList al conjunto B
                CConjunto conjunto_b = new CConjunto(tamanio_b);
                for (int k = 0; k < this.jList_conjunto_b.getModel().getSize();k++) {
                    conjunto_b.conjunto[k] = Integer.parseInt(this.jList_conjunto_b.getModel().getElementAt(k));
                }
                
                // Operaciones
                CConjunto conjunto_c = new CConjunto();
                if (indice == 1){
                    // Unión
                    conjunto_c = conjunto_a.Union(conjunto_b);
                } else {
                    if (indice == 2) {
                        // Intersección
                        conjunto_c = conjunto_a.Interseccion(conjunto_b);

                    } else {
                        if (indice == 3) {
                            // A-B
                            conjunto_c = conjunto_a.Diferencia(conjunto_b);
                        } else {
                            if (indice == 4) {
                                // B-A
                                conjunto_c = conjunto_b.Diferencia(conjunto_a);
                            } else {
                                if (indice == 5) {
                                    conjunto_c = conjunto_a.DiferenciaSimetrica(conjunto_b);
                                }
                            }
                        }
                    }
                }
                
                // Mostrar resultado
                for (int k = 0; k < conjunto_c.tamanio; k++) {
                     model_conjunto_c.addElement(conjunto_c.conjunto[k]);
                     System.out.print(conjunto_c.conjunto[k]);
                }
            }
        } else if (evt.getStateChange() == evt.DESELECTED) {
            // Item is no longer selected
        }
    }//GEN-LAST:event_jComboBox_operacionesItemStateChanged

    private void jButton_limpiar_todoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_limpiar_todoMouseClicked
        // TODO add your handling code here:
        model_conjunto_a.clear();
        model_conjunto_b.clear();
        model_conjunto_c.clear();
    }//GEN-LAST:event_jButton_limpiar_todoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_agregar_a;
    private javax.swing.JButton jButton_agregar_b;
    private javax.swing.JButton jButton_eliminar_a;
    private javax.swing.JButton jButton_eliminar_b;
    private javax.swing.JButton jButton_limpiar_a;
    private javax.swing.JButton jButton_limpiar_b;
    private javax.swing.JButton jButton_limpiar_todo;
    private javax.swing.JComboBox<String> jComboBox_operaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList_conjunto_a;
    private javax.swing.JList<String> jList_conjunto_b;
    private javax.swing.JList<Integer> jList_conjunto_c;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField_elemento_a;
    private javax.swing.JTextField jTextField_elemento_b;
    // End of variables declaration//GEN-END:variables
}
